apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: transanalyzerpt-training
  annotations:
    scenarios.ai.sap.com/description: "transanalyzerpt Training Pipeline"
    scenarios.ai.sap.com/name: "transanalyzerpt"
    executables.ai.sap.com/description: "Train the transanalyzerpt model"
    executables.ai.sap.com/name: "transanalyzerpt-training"
  labels:
    scenarios.ai.sap.com/id: "transanalyzerpt"
    ai.sap.com/version: "1.0.0"
spec:
  entrypoint: training-pipeline
  templates:
    - name: training-pipeline
      steps:
        - - name: train
            template: train-step

    - name: train-step
      metadata:
        labels:
          ai.sap.com/resourcePlan: starter
      container:
        image: docker.io/jerushan/transanalyzerpt-train:latest
        command: ["python"]
        args:
          - "training/trainer.py"
        env:
          - name: MODEL_OUTPUT_PATH
            value: "/tmp/models"
      outputs:
        artifacts:
          - name: model-output
            globalName: trainedmodels
            path: /tmp/models          # ← only output models here
            archive:
              none: {}
