apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: transaction-analyzer-training
  labels:
    scenarios.ai.sap.com/id: "transaction-analyzer"
    executables.ai.sap.com/id: "transaction-analyzer-training"
    ai.sap.com/version: "1.0.0"
  annotations:
    executables.ai.sap.com/name: "transaction-analyzer-training"
spec:
  template:
    apiVersion: serving.kserve.io/v1beta1
    kind: InferenceService
    metadata:
      name: transaction-analyzer-training
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/targetBurstCapacity: "0"
    spec: |
      predictor:
        containers:
          - name: kserve-container
            image: docker.io/rahulcruze786/training-service:v1.3
            ports:
              - containerPort: 8080
                protocol: TCP
            env:
              - name: MODEL_DIR
                value: /app/models
              - name: AWS_ACCESS_KEY_ID
                valueFrom:
                  secretKeyRef:
                    name: s3-transaction-analyzer
                    key: access_key_id
              - name: AWS_SECRET_ACCESS_KEY
                valueFrom:
                  secretKeyRef:
                    name: s3-transaction-analyzer
                    key: secret_access_key
              - name: AWS_DEFAULT_REGION
                valueFrom:
                  secretKeyRef:
                    name: s3-transaction-analyzer
                    key: region
              - name: S3_BUCKET
                valueFrom:
                  secretKeyRef:
                    name: s3-transaction-analyzer
                    key: bucket
              - name: S3_ENDPOINT
                valueFrom:
                  secretKeyRef:
                    name: s3-transaction-analyzer
                    key: host
              - name: S3_PATH_PREFIX
                value: "ai/transaction-analyzer"
